### ISSUE TITLE
Allow more recent React minor version?

### ISSUE THREAD

**Issue by pierluigi** [rocjs/roc-plugin-react#6]
https://github.com/rocjs/roc-plugin-react/blob/master/extensions/roc-plugin-react/package.json#L26 

Why use `~` instead of `^`? This locks React to `15.0.X` which is at present 2 minor versions behind latest stable (`15.3.2` atm).

**Comment by dlmr** [comment]
In general we have selected to go for `~` over `^` since we have been burned by feature updates to include breaking changes. However in the case of React I think we can trust that Facebook will follow SemVer correctly and it should be find to change the version range.

The only other thing is that we have discussed if we should provide the React dependency as we are doing right now or if we should require it instead. I'm leaning forwards making it a required dependency over exporting it.

**Comment by dlmr** [comment]
Closed by #7
